---
name: Build & Publish Web Base

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 1,15 * *"  # Every 2 weeks
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-and-publish-web-base.yml
      - .github/workflows/internal-build-and-publish.yml
      - 'common/**'
      - 'web-base/**'
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: ./.github/workflows/internal-build-and-publish.yml
    strategy:
      matrix:
        info:
          - version: latest
            unsecured: false
          - version: latest-unsecured
            unsecured: true
    with:
      image: web-base
      version: ${{ matrix.info.version }}
      build-args: |
        UNSECURED=${{ matrix.info.unsecured }}
