---
name: Build & Publish Postgis Test

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 1,15 * *"  # Every 2 weeks
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-and-publish-postgis-test.yml
      - .github/workflows/internal-build-and-publish.yml
      - 'common/**'
      - 'postgis-test/**'
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: ./.github/workflows/internal-build-and-publish.yml
    with:
      image: postgis-test
      version: latest
