---
name: Build & Publish

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 1,15 * *"  # Every 2 weeks
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - postgis-test
          - web-base
        version: [latest]
        include:
          - image: web-base
            version: unsecured
            unsecured: true
          # We need multiple PHP versions
          - image: php-base
            version: '8.1'
            php-alpine: '81'
            alpine: 3.19
          - image: php-base
            version: '8.2'
            php-alpine: '82'
            alpine: 3.19
          - image: php-base
            version: '8.3'
            php-alpine: '83'
            alpine: 3.19
        # Don't create php-base:latest
        exclude:
          - image: php-base
            version: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.image }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:${{ matrix.version }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
            PHP_VERSION=${{ matrix.php-alpine }}
            UNSECURED=${{ matrix.unsecured }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
