---
name: Lint

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  yaml-lint:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint .

  dockerfile-lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    env:
      HADOLINT_RECURSIVE: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
